apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  SERVER_PORT: "1234"  # Default port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-container
        image: bouncing_ball_server
        imagePullPolicy: Never
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: server-config
                key: SERVER_PORT
        ports:
        - containerPort: 1234  # Use the same port as the environment variable SERVER_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 1234  # Use the same port as the environment variable SERVER_PORT
